# Generated by Django 4.2.6 on 2023-11-07 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carteira', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='id_portfolio',
            field=models.ForeignKey(db_column='id_portfolio', on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio'),
        ),
    ]
