# Generated by Django 4.2.6 on 2023-11-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id_portfolio', models.AutoField(db_column='id_portfolio', primary_key=True, serialize=False)),
                ('nome_portfolio', models.CharField(max_length=255)),
                ('descricao_portfolio', models.TextField()),
            ],
            options={
                'db_table': 'Portfolio',
            },
        ),
    ]
