# Generated by Django 4.2.6 on 2023-11-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id_acao', models.AutoField(db_column='id_acao', primary_key=True, serialize=False)),
                ('nome_acao', models.CharField(max_length=255)),
                ('preco_mais_baixo', models.FloatField()),
                ('preco_mais_alto', models.FloatField()),
                ('descricao_acao', models.TextField()),
                ('simbolo_acao', models.CharField(max_length=20)),
                ('nome_empresa', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Acao',
            },
        ),
    ]
