# Generated by Django 4.2.6 on 2023-11-09 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acao',
            name='descricao_acao',
        ),
    ]
