# Generated by Django 4.2.6 on 2023-11-10 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acao', '0002_remove_acao_descricao_acao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acao',
            name='pais_de_origem',
        ),
    ]
