# Generated by Django 4.2.6 on 2023-11-11 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('acao', '0003_remove_acao_pais_de_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='data_acao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
